# Generated by Django 4.2 on 2023-06-08 14:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Collage',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(default=' ', max_length=500)),
                ('image', models.ImageField(default=' ', upload_to='img')),
                ('qr_code', models.ImageField(blank=True, upload_to='qr_codes')),
                ('slug', models.SlugField(default=' ', max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CollageForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=500)),
                ('gpa', models.CharField(max_length=50)),
                ('faculty', models.CharField(max_length=300)),
                ('collage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.collage')),
            ],
        ),
    ]
