# Generated by Django 4.0.3 on 2023-06-09 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='collageform',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
